# Generated by Django 3.0.2 on 2020-02-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddList',
            new_name='List',
        ),
    ]
