# Generated by Django 3.0.2 on 2020-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200226_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
